import type { GuestData, StepId } from "@/types";

export const COLORS = {
  primary: "#fa865c",
  primaryD: "#e5704a",
  primaryLt: "#fef0ea",
  secondary: "#324154",
  secMid: "#4a5a6e",
  secLt: "#6a7a8e",
  bg: "#e5e2dd",
  bgDark: "#23150f",
  white: "#ffffff",
  border: "#d0cbc4",
  borderLt: "#e8e4de",
  text: "#1e2c3a",
  textMid: "#4a5a6a",
  textLow: "#8a9aaa",
  ok: "#2d7a50",
  okBg: "#edf7f1",
  err: "#c0392b",
  errBg: "#fdf2f2",
} as const;

export const MOCK_KNOWN_GUEST: GuestData = {
  nombre: "",
  apellido: "",
  apellido2: "",
  sexo: "",
  fechaNac: "",
  nacionalidad: "Española",
  email: "",
  telefono: "",
  direccion: "",
  ciudad: "",
  provincia: "",
  cp: "",
  pais: "España",
  tipoDoc: "DNI",
  numDoc: "",
  vat: "",
  esMenor: false,
  relacionesConAdultos: [],
};

export const PAISES = [
  "España",
  "Reino Unido",
  "Francia",
  "Alemania",
  "Italia",
  "Países Bajos",
  "Bélgica",
  "Portugal",
  "Irlanda",
  "Estados Unidos",
  "Suiza",
  "Suecia",
  "Noruega",
  "Dinamarca",
  "Austria",
  "Polonia",
  "Finlandia",
  "México",
  "Argentina",
  "Colombia",
];

export const NACIONALIDADES = [
  "Española",
  "Alemana",
  "Francesa",
  "Italiana",
  "Portuguesa",
  "Inglesa",
  "Estadounidense",
  "Argentina",
  "Mexicana",
  "Otra",
];

export const TIPOS_DOCUMENTO = [
  "DNI",
  "NIF",
  "CIF",
  "Pasaporte",
  "NIE",
  "Otro",
];

export const HORAS_LLEGADA = [
  "No especificada",
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
  "19:30",
  "20:00",
  "20:30",
  "21:00",
  "21:30",
  "22:00",
  "22:30",
  "23:00",
  "Después de medianoche",
];

export const SEXOS = ["Hombre", "Mujer", "No indicar"];

export const RELACIONES_MENOR = ["Hijo/a", "Sobrino/a", "Tutor legal", "Otra"];

export const PARENTESCOS_MENOR = [
  "Abuelo/a",
  "Bisabuelo/a",
  "Bisnieto/a",
  "Cuñado/a",
  "Cónyuge/a",
  "Hijo/a",
  "Hermano/a",
  "Nieto/a",
  "Padre o Madre",
  "Sobrino/a",
  "Suegro/a",
  "Tío/a",
  "Yerno o nuera",
  "Tutor/a",
  "Otro",
];

export const FLOW_STEPS_LINK: StepId[] = [
  "inicio",
  "bienvenida",
  "form_personal",
  "form_contacto",
  "form_extras",
  "revision",
  "exito",
];
export const DOT_STEPS_BASE: StepId[] = [
  "inicio",
  "bienvenida",
  "form_personal",
  "form_contacto",
  "form_extras",
  "revision",
  "exito",
];

export const DOT_LABELS: Partial<Record<StepId, string>> = {
  inicio: "Inicio",
  bienvenida: "Bienvenida",
  form_personal: "Datos personales",
  form_contacto: "Contacto",
  form_extras: "Preferencias",
  revision: "Revisión",
  exito: "Completado",
};
