import type { GuestData, StepId } from "@/types";

export const COLORS = {
  primary: "#fa865c",
  primaryD: "#e5704a",
  primaryLt: "#fef0ea",
  secondary: "#324154",
  secMid: "#4a5a6e",
  secLt: "#6a7a8e",
  bg: "#e5e2dd",
  bgDark: "#23150f",
  white: "#ffffff",
  border: "#d0cbc4",
  borderLt: "#e8e4de",
  text: "#1e2c3a",
  textMid: "#4a5a6a",
  textLow: "#8a9aaa",
  ok: "#2d7a50",
  okBg: "#edf7f1",
  err: "#c0392b",
  errBg: "#fdf2f2",
} as const;

// FIX: pais usa código ISO2 "ES", no el string "España".
// Todos los selectores de país en el frontend usan códigos ISO2.
export const MOCK_KNOWN_GUEST: GuestData = {
  nombre: "",
  apellido: "",
  apellido2: "",
  sexo: "",
  fechaNac: "",
  nacionalidad: "Española",
  email: "",
  telefono: "",
  direccion: "",
  ciudad: "",
  provincia: "",
  cp: "",
  pais: "ES", // ← FIX: antes era "España", rompía el selector en modo dev
  tipoDoc: "DNI",
  numDoc: "",
  vat: "",
  esMenor: false,
  relacionesConAdultos: [],
};

export const PAISES = [
  "España",
  "Reino Unido",
  "Francia",
  "Alemania",
  "Italia",
  "Países Bajos",
  "Bélgica",
  "Portugal",
  "Irlanda",
  "Estados Unidos",
  "Suiza",
  "Suecia",
  "Noruega",
  "Dinamarca",
  "Austria",
  "Polonia",
  "Finlandia",
  "México",
  "Argentina",
  "Colombia",
];

export const NACIONALIDADES = [
  "Española",
  "Alemana",
  "Francesa",
  "Italiana",
  "Portuguesa",
  "Inglesa",
  "Estadounidense",
  "Argentina",
  "Mexicana",
  "Otra",
];

export const TIPOS_DOCUMENTO = [
  "DNI",
  "NIF",
  "CIF",
  "Pasaporte",
  "NIE",
  "Otro",
];

export const HORAS_LLEGADA = [
  "No especificada",
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
  "19:30",
  "20:00",
  "20:30",
  "21:00",
  "21:30",
  "22:00",
  "22:30",
  "23:00",
  "Después de medianoche",
];

export const SEXOS = ["Hombre", "Mujer", "No indicar"];

export const PREFIJOS_TELEFONICOS = [
  { code: "AF", dial: "+93" },
  { code: "AL", dial: "+355" },
  { code: "DZ", dial: "+213" },
  { code: "AD", dial: "+376" },
  { code: "AO", dial: "+244" },
  { code: "AI", dial: "+1 264" },
  { code: "AG", dial: "+1 268" },
  { code: "AR", dial: "+54" },
  { code: "AM", dial: "+374" },
  { code: "AW", dial: "+297" },
  { code: "AU", dial: "+61" },
  { code: "AT", dial: "+43" },
  { code: "AZ", dial: "+994" },
  { code: "BS", dial: "+1 242" },
  { code: "BH", dial: "+973" },
  { code: "BD", dial: "+880" },
  { code: "BB", dial: "+1 246" },
  { code: "BY", dial: "+375" },
  { code: "BE", dial: "+32" },
  { code: "BZ", dial: "+501" },
  { code: "BJ", dial: "+229" },
  { code: "BM", dial: "+1 441" },
  { code: "BT", dial: "+975" },
  { code: "BO", dial: "+591" },
  { code: "BA", dial: "+387" },
  { code: "BW", dial: "+267" },
  { code: "BR", dial: "+55" },
  { code: "BN", dial: "+673" },
  { code: "BG", dial: "+359" },
  { code: "BF", dial: "+226" },
  { code: "BI", dial: "+257" },
  { code: "KH", dial: "+855" },
  { code: "CM", dial: "+237" },
  { code: "CA", dial: "+1" },
  { code: "CV", dial: "+238" },
  { code: "KY", dial: "+1 345" },
  { code: "CF", dial: "+236" },
  { code: "TD", dial: "+235" },
  { code: "CL", dial: "+56" },
  { code: "CN", dial: "+86" },
  { code: "CO", dial: "+57" },
  { code: "KM", dial: "+269" },
  { code: "CG", dial: "+242" },
  { code: "CD", dial: "+243" },
  { code: "CK", dial: "+682" },
  { code: "CR", dial: "+506" },
  { code: "HR", dial: "+385" },
  { code: "CU", dial: "+53" },
  { code: "CW", dial: "+599" },
  { code: "CY", dial: "+357" },
  { code: "CZ", dial: "+420" },
  { code: "DK", dial: "+45" },
  { code: "DJ", dial: "+253" },
  { code: "DM", dial: "+1 767" },
  { code: "DO", dial: "+1" },
  { code: "EC", dial: "+593" },
  { code: "EG", dial: "+20" },
  { code: "SV", dial: "+503" },
  { code: "GQ", dial: "+240" },
  { code: "ER", dial: "+291" },
  { code: "EE", dial: "+372" },
  { code: "SZ", dial: "+268" },
  { code: "ET", dial: "+251" },
  { code: "FK", dial: "+500" },
  { code: "FO", dial: "+298" },
  { code: "FJ", dial: "+679" },
  { code: "FI", dial: "+358" },
  { code: "FR", dial: "+33" },
  { code: "GF", dial: "+594" },
  { code: "PF", dial: "+689" },
  { code: "GA", dial: "+241" },
  { code: "GM", dial: "+220" },
  { code: "GE", dial: "+995" },
  { code: "DE", dial: "+49" },
  { code: "GH", dial: "+233" },
  { code: "GI", dial: "+350" },
  { code: "GR", dial: "+30" },
  { code: "GL", dial: "+299" },
  { code: "GD", dial: "+1 473" },
  { code: "GP", dial: "+590" },
  { code: "GU", dial: "+1 671" },
  { code: "GT", dial: "+502" },
  { code: "GN", dial: "+224" },
  { code: "GW", dial: "+245" },
  { code: "GY", dial: "+592" },
  { code: "HT", dial: "+509" },
  { code: "HN", dial: "+504" },
  { code: "HK", dial: "+852" },
  { code: "HU", dial: "+36" },
  { code: "IS", dial: "+354" },
  { code: "IN", dial: "+91" },
  { code: "ID", dial: "+62" },
  { code: "IR", dial: "+98" },
  { code: "IQ", dial: "+964" },
  { code: "IE", dial: "+353" },
  { code: "IL", dial: "+972" },
  { code: "IT", dial: "+39" },
  { code: "JM", dial: "+1 876" },
  { code: "JP", dial: "+81" },
  { code: "JO", dial: "+962" },
  { code: "KZ", dial: "+7" },
  { code: "KE", dial: "+254" },
  { code: "KI", dial: "+686" },
  { code: "KP", dial: "+850" },
  { code: "KR", dial: "+82" },
  { code: "KW", dial: "+965" },
  { code: "KG", dial: "+996" },
  { code: "LA", dial: "+856" },
  { code: "LV", dial: "+371" },
  { code: "LB", dial: "+961" },
  { code: "LS", dial: "+266" },
  { code: "LR", dial: "+231" },
  { code: "LY", dial: "+218" },
  { code: "LI", dial: "+423" },
  { code: "LT", dial: "+370" },
  { code: "LU", dial: "+352" },
  { code: "MO", dial: "+853" },
  { code: "MG", dial: "+261" },
  { code: "MW", dial: "+265" },
  { code: "MY", dial: "+60" },
  { code: "MV", dial: "+960" },
  { code: "ML", dial: "+223" },
  { code: "MT", dial: "+356" },
  { code: "MH", dial: "+692" },
  { code: "MQ", dial: "+596" },
  { code: "MR", dial: "+222" },
  { code: "MU", dial: "+230" },
  { code: "YT", dial: "+262" },
  { code: "MX", dial: "+52" },
  { code: "FM", dial: "+691" },
  { code: "MD", dial: "+373" },
  { code: "MC", dial: "+377" },
  { code: "MN", dial: "+976" },
  { code: "ME", dial: "+382" },
  { code: "MS", dial: "+1 664" },
  { code: "MA", dial: "+212" },
  { code: "MZ", dial: "+258" },
  { code: "MM", dial: "+95" },
  { code: "NA", dial: "+264" },
  { code: "NR", dial: "+674" },
  { code: "NP", dial: "+977" },
  { code: "NL", dial: "+31" },
  { code: "NZ", dial: "+64" },
  { code: "NI", dial: "+505" },
  { code: "NE", dial: "+227" },
  { code: "NG", dial: "+234" },
  { code: "NU", dial: "+683" },
  { code: "NO", dial: "+47" },
  { code: "OM", dial: "+968" },
  { code: "PK", dial: "+92" },
  { code: "PW", dial: "+680" },
  { code: "PA", dial: "+507" },
  { code: "PG", dial: "+675" },
  { code: "PY", dial: "+595" },
  { code: "PE", dial: "+51" },
  { code: "PH", dial: "+63" },
  { code: "PL", dial: "+48" },
  { code: "PT", dial: "+351" },
  { code: "PR", dial: "+1 787" },
  { code: "QA", dial: "+974" },
  { code: "RO", dial: "+40" },
  { code: "RU", dial: "+7" },
  { code: "RW", dial: "+250" },
  { code: "RE", dial: "+262" },
  { code: "KN", dial: "+1 869" },
  { code: "LC", dial: "+1 758" },
  { code: "VC", dial: "+1 784" },
  { code: "WS", dial: "+685" },
  { code: "SM", dial: "+378" },
  { code: "ST", dial: "+239" },
  { code: "SA", dial: "+966" },
  { code: "SN", dial: "+221" },
  { code: "RS", dial: "+381" },
  { code: "SC", dial: "+248" },
  { code: "SL", dial: "+232" },
  { code: "SG", dial: "+65" },
  { code: "SK", dial: "+421" },
  { code: "SI", dial: "+386" },
  { code: "SB", dial: "+677" },
  { code: "SO", dial: "+252" },
  { code: "ZA", dial: "+27" },
  { code: "SS", dial: "+211" },
  { code: "ES", dial: "+34" },
  { code: "LK", dial: "+94" },
  { code: "SD", dial: "+249" },
  { code: "SR", dial: "+597" },
  { code: "SE", dial: "+46" },
  { code: "CH", dial: "+41" },
  { code: "SY", dial: "+963" },
  { code: "TJ", dial: "+992" },
  { code: "TZ", dial: "+255" },
  { code: "TH", dial: "+66" },
  { code: "TL", dial: "+670" },
  { code: "TG", dial: "+228" },
  { code: "TO", dial: "+676" },
  { code: "TT", dial: "+1 868" },
  { code: "TN", dial: "+216" },
  { code: "TR", dial: "+90" },
  { code: "TM", dial: "+993" },
  { code: "TC", dial: "+1 649" },
  { code: "TV", dial: "+688" },
  { code: "UG", dial: "+256" },
  { code: "UA", dial: "+380" },
  { code: "AE", dial: "+971" },
  { code: "GB", dial: "+44" },
  { code: "US", dial: "+1" },
  { code: "UY", dial: "+598" },
  { code: "UZ", dial: "+998" },
  { code: "VU", dial: "+678" },
  { code: "VA", dial: "+379" },
  { code: "VE", dial: "+58" },
  { code: "VN", dial: "+84" },
  { code: "WF", dial: "+681" },
  { code: "YE", dial: "+967" },
  { code: "ZM", dial: "+260" },
  { code: "ZW", dial: "+263" },
];

export const FLOW_STEPS_LINK: StepId[] = [
  "inicio",
  "bienvenida",
  "form_personal",
  "form_contacto",
  "form_extras",
  "revision",
  "exito",
];
export const DOT_STEPS_BASE: StepId[] = [
  "inicio",
  "bienvenida",
  "form_personal",
  "form_contacto",
  "form_extras",
  "revision",
  "exito",
];

export const DOT_LABELS: Partial<Record<StepId, string>> = {
  inicio: "Inicio",
  bienvenida: "Bienvenida",
  form_personal: "Datos personales",
  form_contacto: "Contacto",
  form_extras: "Preferencias",
  revision: "Revisión",
  exito: "Completado",
};
